package pi

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mainline-org/mainline/internal/hooks"
)

const (
	piDirName          = ".pi"
	extensionsDirName  = "extensions"
	extensionFileName  = "mainline.ts"
	managedMarker      = "mainline-managed-pi-extension"
	commandModeVarName = "MAINLINE_COMMAND_MODE"
)

func (Agent) Install(repoRoot string, opts hooks.InstallOptions) (hooks.InstallReport, error) {
	opts = hooks.ResolveInstallOptions(repoRoot, opts)
	report := hooks.InstallReport{
		Scope:           "repo-local",
		RestartRequired: true,
		CommandMode:     hooks.InstallCommandMode(opts),
	}
	extensionPath := extensionPath(repoRoot)
	desired := extensionSource(opts)

	prev, err := os.ReadFile(extensionPath)
	fileExisted := true
	if err != nil {
		if os.IsNotExist(err) {
			fileExisted = false
		} else {
			return report, fmt.Errorf("read %s: %w", extensionPath, err)
		}
	}

	if fileExisted {
		text := string(prev)
		if !isManagedExtension(text) && !opts.Force {
			return report, fmt.Errorf("refusing to overwrite unmanaged Pi extension at %s (pass --force to replace it)", extensionPath)
		}
		if text == desired {
			report.AlreadyInstalled = true
			report.Files = []string{extensionPath}
			report.HookCount = len((Agent{}).HookNames())
			return report, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(extensionPath), 0o755); err != nil {
		return report, fmt.Errorf("create .pi/extensions dir: %w", err)
	}
	if err := os.WriteFile(extensionPath, []byte(desired), 0o644); err != nil {
		return report, fmt.Errorf("write %s: %w", extensionPath, err)
	}
	report.Files = []string{extensionPath}
	if !fileExisted {
		report.CreatedFiles = []string{extensionPath}
	}
	report.HookCount = len((Agent{}).HookNames())
	return report, nil
}

func (Agent) Uninstall(repoRoot string) error {
	extensionPath := extensionPath(repoRoot)
	data, err := os.ReadFile(extensionPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read %s: %w", extensionPath, err)
	}
	if !isManagedExtension(string(data)) {
		return nil
	}
	if err := os.Remove(extensionPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", extensionPath, err)
	}
	// Best effort cleanup: only succeeds when the directories are empty.
	_ = os.Remove(filepath.Dir(extensionPath))
	_ = os.Remove(filepath.Join(repoRoot, piDirName))
	return nil
}

func (Agent) IsInstalled(repoRoot string) (bool, error) {
	st, err := (Agent{}).InstallationStatus(repoRoot)
	return st.Installed, err
}

func (Agent) InstallationStatus(repoRoot string) (hooks.InstallationStatus, error) {
	extensionPath := extensionPath(repoRoot)
	st := hooks.InstallationStatus{
		Scope:             "repo-local",
		Files:             []string{extensionPath},
		ExpectedHookCount: len((Agent{}).HookNames()),
	}
	data, err := os.ReadFile(extensionPath)
	if err != nil {
		if os.IsNotExist(err) {
			return st, nil
		}
		return st, fmt.Errorf("read %s: %w", extensionPath, err)
	}
	text := string(data)
	if !isManagedExtension(text) {
		st.RepairReasons = []string{".pi/extensions/mainline.ts exists but is not managed by Mainline"}
		st.NeedsRepair = true
		return st, nil
	}
	st.Installed = true
	st.RestartRequired = true
	st.HookCount = st.ExpectedHookCount
	st.CommandMode = extensionCommandMode(text)
	if st.CommandMode == "" || st.CommandMode == hooks.CommandModeUnknown {
		st.RepairReasons = append(st.RepairReasons, "could not determine Pi extension command mode")
	}
	if reason := hooks.RuntimeRepairReason(st.CommandMode); reason != "" {
		st.RepairReasons = append(st.RepairReasons, reason)
	}
	st.NeedsRepair = len(st.RepairReasons) > 0
	return st, nil
}

func extensionPath(repoRoot string) string {
	return filepath.Join(repoRoot, piDirName, extensionsDirName, extensionFileName)
}

func isManagedExtension(text string) bool {
	return strings.Contains(text, managedMarker)
}

func extensionCommandMode(text string) string {
	needle := "const " + commandModeVarName + " = "
	idx := strings.Index(text, needle)
	if idx < 0 {
		return hooks.CommandModeUnknown
	}
	rest := text[idx+len(needle):]
	end := strings.Index(rest, ";")
	if end < 0 {
		return hooks.CommandModeUnknown
	}
	value, err := strconv.Unquote(strings.TrimSpace(rest[:end]))
	if err != nil {
		return hooks.CommandModeUnknown
	}
	switch value {
	case hooks.CommandModePath, hooks.CommandModeLocalDev, hooks.CommandModeBin:
		return value
	default:
		return hooks.CommandModeUnknown
	}
}

func extensionSource(opts hooks.InstallOptions) string {
	command, argsPrefix := piInvocation(opts)
	mode := hooks.InstallCommandMode(opts)
	return fmt.Sprintf(`// %s
// Generated by Mainline. Re-run "mainline hooks install --agent pi" to update.

import { spawn } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const %s = %s;
const MAINLINE_COMMAND = %s;
const MAINLINE_ARGS_PREFIX = %s;
const HOOK_TIMEOUT_MS = 30000;

type HookOutput = {
	systemPromptAppend?: string;
	additionalContext?: string;
	context?: string;
};

function debug(message: string): void {
	if (process.env.MAINLINE_HOOKS_DEBUG) console.error("[mainline pi] " + message);
}

function sessionId(ctx: { sessionManager?: { getSessionFile?: () => string | undefined } }): string | undefined {
	try {
		return ctx.sessionManager?.getSessionFile?.();
	} catch {
		return undefined;
	}
}

function extractContext(out: HookOutput | undefined): string | undefined {
	return out?.systemPromptAppend ?? out?.additionalContext ?? out?.context;
}

async function runMainlineHook(
	hookName: string,
	payload: Record<string, unknown>,
	cwd: string,
): Promise<HookOutput | undefined> {
	return new Promise((resolve) => {
		const child = spawn(MAINLINE_COMMAND, [...MAINLINE_ARGS_PREFIX, hookName], {
			cwd,
			stdio: ["pipe", "pipe", "pipe"],
		});

		let stdout = "";
		let stderr = "";
		const timer = setTimeout(() => {
			debug("timed out running " + hookName);
			child.kill("SIGTERM");
			resolve(undefined);
		}, HOOK_TIMEOUT_MS);

		child.stdout.on("data", (chunk) => {
			stdout += String(chunk);
		});
		child.stderr.on("data", (chunk) => {
			stderr += String(chunk);
		});
		child.on("error", (err) => {
			clearTimeout(timer);
			debug("failed to run " + hookName + ": " + err.message);
			resolve(undefined);
		});
		child.on("close", () => {
			clearTimeout(timer);
			if (stderr.trim()) debug(stderr.trim());
			const text = stdout.trim();
			if (!text) {
				resolve(undefined);
				return;
			}
			try {
				resolve(JSON.parse(text) as HookOutput);
			} catch {
				debug("non-JSON hook output from " + hookName);
				resolve(undefined);
			}
		});
		child.stdin.on("error", (err) => {
			debug("stdin error for " + hookName + ": " + err.message);
		});

		try {
			child.stdin.end(JSON.stringify(payload));
		} catch (err) {
			debug("failed to write payload for " + hookName + ": " + String(err));
			resolve(undefined);
		}
	});
}

export default function mainlinePiExtension(pi: ExtensionAPI) {
	let pendingSessionContext: string | undefined;

	pi.on("session_start", async (event, ctx) => {
		const out = await runMainlineHook(
			"session-start",
			{
				event: "session_start",
				reason: event.reason,
				previous_session_file: event.previousSessionFile,
				session_id: sessionId(ctx),
				cwd: ctx.cwd,
			},
			ctx.cwd,
		);
		pendingSessionContext = extractContext(out);
	});

	pi.on("before_agent_start", async (event, ctx) => {
		const out = await runMainlineHook(
			"user-prompt-submit",
			{
				event: "before_agent_start",
				prompt: event.prompt,
				session_id: sessionId(ctx),
				cwd: ctx.cwd,
			},
			ctx.cwd,
		);
		const parts = [pendingSessionContext, extractContext(out)].filter(
			(part): part is string => typeof part === "string" && part.length > 0,
		);
		pendingSessionContext = undefined;
		if (parts.length === 0) return undefined;
		return { systemPrompt: event.systemPrompt + "\n\n" + parts.join("\n\n") };
	});

	pi.on("agent_end", async (event, ctx) => {
		await runMainlineHook(
			"stop",
			{
				event: "agent_end",
				status: "completed",
				message_count: Array.isArray(event.messages) ? event.messages.length : undefined,
				session_id: sessionId(ctx),
				cwd: ctx.cwd,
			},
			ctx.cwd,
		);
	});

	pi.on("session_before_compact", async (event, ctx) => {
		await runMainlineHook(
			"pre-compact",
			{
				event: "session_before_compact",
				custom_instructions: event.customInstructions,
				session_id: sessionId(ctx),
				cwd: ctx.cwd,
			},
			ctx.cwd,
		);
	});

	pi.on("session_shutdown", async (event, ctx) => {
		await runMainlineHook(
			"session-end",
			{
				event: "session_shutdown",
				reason: event.reason,
				target_session_file: event.targetSessionFile,
				session_id: sessionId(ctx),
				cwd: ctx.cwd,
			},
			ctx.cwd,
		);
	});
}
`, managedMarker, commandModeVarName, quoteTS(mode), quoteTS(command), quoteTSArray(argsPrefix))
}

func piInvocation(opts hooks.InstallOptions) (string, []string) {
	switch {
	case opts.BinPath != "":
		return opts.BinPath, []string{"hooks", AgentName}
	case opts.LocalDev:
		return "go", []string{"run", ".", "hooks", AgentName}
	default:
		return "mainline", []string{"hooks", AgentName}
	}
}

func quoteTS(s string) string {
	return strconv.Quote(s)
}

func quoteTSArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, v := range values {
		quoted = append(quoted, strconv.Quote(v))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
